# -*- coding: utf-8 -*-
"""
方法论库 · 数据集（Method KB seed data）
=========================================
纯数据模块：条目 / 元能力图谱 / 任务-能力映射。**不含逻辑**，供 `build_method_kb.py` 灌库。

数据纪律（本库的红线，写新条目时必须遵守）：
  1. `evidence_tier` 必填：A 元分析/RCT｜B 一致实证（多项独立研究）｜C 教科书/权威综述共识｜D 专家经验
  2. `citation` 必填且**不得编造**。verification 字段如实标注取证状态：
       verified   —— 已由权威源核对（PubMed / Wikipedia 条目 / 出版方页面）
       canonical  —— 公认经典文献，本次**未能**在检索预算内复核（网络引擎触发 bot_challenge），
                     按学术通识录入，待补验；不代表「已验证」
       practitioner —— 无同行评议证据，属从业者/流行方法，只作 D 级经验
  3. `status`：verified | contested | deprecated。`contested`（有争议）必须写进 `contraindications`。
  4. **已证伪 / 过度简化**的内容一律**不入库**（见文末 REJECTED）。
  5. parameters 是**可编译进排程引擎**的字段，只放能被机器消费的结构化值。
  6. 文本内强调一律用「」（U+300C/U+300D），**禁止**在字符串内出现 ASCII 双引号。

取证说明（2026-09-20）：本轮用 search 工作流（agent-search MCP）核对了测试效应、间隔效应、
认知负荷、自我决定论、实施意图、拖延、记忆巩固、间隔重复；sogou/baidu/bing/duckduckgo 在若干次
调用后统一触发 `bot_challenge` / `budget_exhausted`，故其余条目退化为 `canonical` 并由人工把关。
"""

# ============================================================
# 一、元能力图谱（L4 骨架）—— 任务与训练法之间的桥
# ============================================================
META_ABILITIES = [
    {"id": "logical-reasoning",       "name": "逻辑推理",     "category": "思维", "description": "从前提推导结论、识别论证结构、发现谬误。"},
    {"id": "abstraction-modeling",    "name": "抽象建模",     "category": "思维", "description": "把现实问题抽象成变量与关系，建立可求解的模型。"},
    {"id": "stats-inference",         "name": "数理统计",     "category": "思维", "description": "描述数据、理解分布、做推断并量化不确定性。"},
    {"id": "spatial-reasoning",       "name": "空间想象",     "category": "思维", "description": "在脑中操作图形、场与三维结构。"},
    {"id": "computational-thinking",  "name": "计算思维",     "category": "思维", "description": "把问题转成可执行步骤，用程序/数值方法求解。"},
    {"id": "problem-decomposition",   "name": "问题分解",     "category": "方法", "description": "把大问题切成可独立攻克的子问题并排序。"},
    {"id": "experiment-design",       "name": "实验设计",     "category": "方法", "description": "控制变量、设置对照、评估误差与可重复性。"},
    {"id": "literature-synthesis",    "name": "文献综合",     "category": "方法", "description": "检索、筛选、批判性整合已有研究。"},
    {"id": "argumentation",           "name": "表达论证",     "category": "输出", "description": "结构化地陈述主张、证据与推理，含书面与口头。"},
    {"id": "memory-encoding",         "name": "记忆编码",     "category": "基础", "description": "把信息有效写入长期记忆并稳定提取。"},
    {"id": "attention-sustain",       "name": "专注维持",     "category": "基础", "description": "在干扰中维持注意、进入并保持心流。"},
    {"id": "metacognitive-regulation","name": "元认知调控",   "category": "基础", "description": "监控自己的理解程度并据此调整策略（计划-监控-调节）。"},
]

# ============================================================
# 二、任务-能力映射（L3 竞赛 → 所需元能力）
# ============================================================
TASKS = [
    {"slug": "mcm",          "name": "数学建模竞赛", "abilities": [("abstraction-modeling", 1.0), ("stats-inference", 0.9), ("computational-thinking", 0.8), ("argumentation", 0.8), ("literature-synthesis", 0.5)]},
    {"slug": "guangdianbei", "name": "光电杯",       "abilities": [("abstraction-modeling", 0.7), ("experiment-design", 0.7), ("argumentation", 0.6), ("problem-decomposition", 0.6)]},
    {"slug": "cet",          "name": "四六级",       "abilities": [("memory-encoding", 0.8), ("attention-sustain", 0.6), ("argumentation", 0.5)]},
    {"slug": "final-exam",   "name": "期末考试",     "abilities": [("memory-encoding", 0.9), ("metacognitive-regulation", 0.7), ("attention-sustain", 0.6)]},
    {"slug": "grad-school",  "name": "保研考研",     "abilities": [("metacognitive-regulation", 0.8), ("memory-encoding", 0.8), ("attention-sustain", 0.7)]},
]


def _e(slug, type, domain, scope, title, summary, principle, steps,
       tier, citation, status, abilities, parameters=None,
       applicable_when=None, contraindications="", tasks=None):
    """条目构造器（保证字段齐全；缺省统一为「不限」而非空）"""
    return {
        "slug": slug, "type": type, "domain": domain, "discipline_scope": scope,
        "title": title, "summary": summary, "principle": principle,
        "steps": steps, "parameters": parameters or {},
        "applicable_when": applicable_when or {"phase": ["any"], "persona": {}, "task": []},
        "contraindications": contraindications,
        "evidence_tier": tier, "citation": citation, "status": status,
        "abilities": abilities, "tasks": tasks or [],
    }


# ============================================================
# 三、条目（40 条：L0 机制 20 / L1 通用法 11 / L2 学科学法 3 / L3 竞赛 5）
# ============================================================
ENTRIES = [

    # ---------------- L0 认知机制 ----------------
    _e("working-memory-limit", "principle", "cognitive", "通用",
       "工作记忆只有 4 个左右的槽位",
       "同时能主动处理的信息单元极少，超出就会漏。学不动往往是「超载」，不是「笨」。",
       "工作记忆是思考的临时工作台。Miller(1956) 提出 7±2，Cowan(2001) 的收敛证据把上限修正为约 4 个组块。",
       ["把新内容切成不超过 4 个组块一次处理", "先把一个概念吃透，再加下一个", "用草稿纸把中间步骤外化，释放槽位", "组块化：把零散信息打包成一个有意义的单元"],
       "C", {"authors": "Miller, G. A. (1956); Cowan, N. (2001)", "title": "The magical number seven, plus or minus two / The magical number 4 in short-term memory", "source": "Psychological Review / Behavioral and Brain Sciences", "year": "1956 / 2001", "url": "https://en.wikipedia.org/wiki/Working_memory", "verification": "canonical"},
       "verified", [("memory-encoding", "require"), ("problem-decomposition", "train")],
       {"maxNewConceptsPerBlock": 4, "maxConsecutiveBlockMin": 45},
       contraindications="不适用于已高度自动化的技能练习（那类靠程序性记忆，不占工作记忆）。"),

    _e("cognitive-load-theory", "principle", "cognitive", "通用",
       "认知负荷理论：先降无关负荷，再谈努力",
       "学习效果差常常来自「呈现方式」而非「内容难度」；先把无谓的负荷砍掉。",
       "Sweller 于 1980 年代末提出：内在负荷（内容本身）／外在负荷（呈现方式）／相关负荷（构建图式）。外在负荷是可优化的部分。",
       ["检查任务是否把信息塞在乱糟糟的资料里，先整理", "一次只引入一个新概念", "用图示替代纯文字描述结构关系（但同一材料别图文重复）", "把复杂例题拆成有解法的步骤序列（work-example 效应）"],
       "C", {"authors": "Sweller, J.", "title": "Cognitive load during problem solving: Effects on learning", "source": "Cognitive Science", "year": "1988", "url": "https://en.wikipedia.org/wiki/Cognitive_load", "verification": "verified"},
       "verified", [("memory-encoding", "require"), ("attention-sustain", "train"), ("problem-decomposition", "train")],
       {"maxNewConceptsPerBlock": 5, "maxConsecutiveBlockMin": 90},
       contraindications="过度拆解会剥夺必要的思考（专家反而受益于完整问题）——脚手架要随熟练度撤除。"),

    _e("spacing-effect", "principle", "cognitive", "通用",
       "间隔效应：分散学比集中学记得久",
       "同样总时长，拆成多次、拉开间隔，长期记忆显著更好。",
       "Ebbinghaus(1885) 首次系统记录；反复的「学习—遗忘—再提取」会让记忆痕迹随时间重新巩固。",
       ["把一次 3 小时改为连续几天各 40 分钟", "复习间隔逐次拉长（1-3-7-15 天）", "新学内容当天做一次短回顾", "把整门课的复习摊到整学期，而非考前一周"],
       "A", {"authors": "Ebbinghaus, H. (1885); Cepeda, N. J. et al. (2006)", "title": "Über das Gedächtnis / Distributed practice in verbal recall tasks (meta-analysis)", "source": "Psychological Bulletin", "year": "1885 / 2006", "url": "https://en.wikipedia.org/wiki/Spacing_effect", "verification": "verified"},
       "verified", [("memory-encoding", "train"), ("metacognitive-regulation", "train")],
       {"intervalsDays": [1, 3, 7, 15], "minGapHours": 12, "maxSessionMin": 50},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["cet", "final-exam", "grad-school"]}),

    _e("retrieval-practice", "principle", "cognitive", "通用",
       "检索练习（测试效应）：考自己比再读一遍强",
       "主动回忆一次，胜过被动重读多次；重读会制造「我懂了」的错觉。",
       "Roediger & Karpicke(2006) 用教育材料做两组对照：延迟测验中，先前做过测试的组显著优于重复学习的组，尽管重复学习组更自信。",
       ["合上书，默写或复述刚学的要点", "用真题或自测题替代划重点", "每学完一节，先不看答案自问 3 个问题", "把「不会」的地方单独标记，下次专攻"],
       "A", {"authors": "Roediger, H. L., & Karpicke, J. D.", "title": "Test-enhanced learning: Taking memory tests improves long-term retention", "source": "Psychological Science", "year": "2006", "url": "https://pubmed.ncbi.nlm.nih.gov/16507066/", "verification": "verified"},
       "verified", [("memory-encoding", "train"), ("metacognitive-regulation", "train")],
       {"minQuizzesPerTopic": 3, "selfTestRatio": 0.5},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["final-exam", "cet", "grad-school"]},
       contraindications="对完全陌生的材料，先要有最小知识底座再做检索练习，否则只会挫败。"),

    _e("interleaving", "principle", "cognitive", "通用",
       "交错练习：把不同类型的题混着做",
       "同类型题连着刷会「手感很好、考试就废」；混着练更接近真实考试。",
       "Rohrer & Taylor(2007) 发现，数学中交错练习相比分块练习，显著提升迁移与延迟测验成绩，尽管练习时正确率更低（合意困难）。",
       ["每 30 分钟换一个题型或科目，不要一整天只钻一类", "复习时打乱章节顺序", "把易混概念放在一起对比", "接受练习时「更累、错更多」是正常的"],
       "B", {"authors": "Rohrer, D., & Taylor, K.", "title": "The shuffling of mathematics problems improves learning", "source": "Instructional Science", "year": "2007", "url": "", "verification": "canonical"},
       "verified", [("memory-encoding", "train"), ("problem-decomposition", "train")],
       {"sessionMixRatio": 0.5, "blockMin": 30},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["final-exam", "cet"]},
       contraindications="初学某类新技能时先做分块练习建立基本套路，过早交错会让新手无从下手。"),

    _e("deliberate-practice", "principle", "psych", "通用",
       "刻意练习：练自己最弱、且有反馈的那部分",
       "重复已经会的不是练习，是舒适。进步发生在「略超出能力、且有纠正反馈」的区间。",
       "Ericsson、Krampe & Tesch-Römer(1993) 研究专家表现，指出有效练习需明确目标、即时反馈、反复纠错，而非单纯堆时间。",
       ["先定位最薄弱的环节，而不是从头再练一遍", "每次练习设一个具体、可检验的小目标", "拿真题或标准答案当反馈，对照差距", "记录错因，下次专练这个错因"],
       "B", {"authors": "Ericsson, K. A., Krampe, R. T., & Tesch-Römer, C.", "title": "The role of deliberate practice in the acquisition of expert performance", "source": "Psychological Review", "year": "1993", "url": "", "verification": "canonical"},
       "verified", [("metacognitive-regulation", "train"), ("problem-decomposition", "train")],
       {"weaknessFocusRatio": 0.6, "feedbackLoopMaxDays": 3},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["final-exam", "grad-school", "mcm"]},
       contraindications="「1 万小时」是流行误读——Ericsson 本人反对把它简化为时长数字；练习的质量才是变量。"),

    _e("generation-effect", "principle", "cognitive", "通用",
       "生成效应：自己造出来的记得更牢",
       "由自己生成答案（而非读现成答案）的记忆更持久。",
       "Slamecka & Graf(1978) 的经典实验：自己补全的词，比直接读到的词回忆率更高。生成过程本身就是一次深加工。",
       ["先尝试自己推导，再看解答", "把定义改成填空或自问式笔记", "用自己的话复述，而非照抄", "做题时先写下思路再对答案"],
       "B", {"authors": "Slamecka, N. J., & Graf, P.", "title": "The generation effect: Delineation of a phenomenon", "source": "Journal of Experimental Psychology: Human Learning and Memory", "year": "1978", "url": "", "verification": "canonical"},
       "verified", [("memory-encoding", "train"), ("argumentation", "train")],
       {},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["final-exam", "cet"]}),

    _e("desirable-difficulty", "principle", "cognitive", "通用",
       "合意困难：学得「有点费劲」才记得牢",
       "让学习变简单（划重点、重读、连刷同类题）会降低长期保持。适度困难反而有益。",
       "Bjork 提出：如果训练条件让表现（performance）当场变好，常伴随长期学习（learning）变差。二者不是一回事。",
       ["别用「今天很顺」当学习有效的证据", "加入间隔、交错、检索这些制造难度的做法", "用延迟测验检验，而非当场感觉", "接受短期正确率下降是投资"],
       "B", {"authors": "Bjork, R. A., & Bjork, E. L.", "title": "Desirable difficulties in theory and practice", "source": "Journal of Applied Research in Memory and Cognition", "year": "2020", "url": "", "verification": "canonical"},
       "verified", [("metacognitive-regulation", "train"), ("memory-encoding", "require")],
       {},
       contraindications="难度要「合意」——远超当前能力会造成挫败与放弃，属于不良困难（undesirable difficulty）。"),

    _e("elaborative-interrogation", "principle", "cognitive", "通用",
       "精细追问：不停问「为什么」",
       "对事实追问「为什么是这样、和我知道的有什么联系」，能显著提升记忆与理解。",
       "Dunlosky 等(2013) 的权威综述把 elaborative interrogation 与 self-explanation 列为中等效用但易上手的技术：把新知识与旧知识建立因果与关联链接。",
       ["每读到一个结论，先问「为什么成立」", "再问「这和我已经会的 X 有什么关系」", "把答案写下来（写作逼出漏洞）", "对自己讲一遍完整因果链"],
       "C", {"authors": "Dunlosky, J., Rawson, K. A., Marsh, E. J., Nathan, M. J., & Willingham, D. T.", "title": "Improving students' learning with effective learning techniques", "source": "Psychological Science in the Public Interest", "year": "2013", "url": "", "verification": "canonical"},
       "verified", [("memory-encoding", "train"), ("argumentation", "train"), ("metacognitive-regulation", "train")],
       {},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["final-exam", "mcm"]}),

    _e("dual-coding", "principle", "cognitive", "通用",
       "双重编码：文字配结构图，别重复别堆砌",
       "同一信息同时用言语与视觉两条通道编码，记忆更强。",
       "Paivio 的双重编码理论 + Mayer 的多媒体学习原则：图与文互补有效，图与文重复（把讲的话原样印成字）反而有害（冗余效应）。",
       ["把流程或结构画成图，而不是再抄一遍文字", "图中只放关键词，讲解放口头稿", "避免一页 PPT 全是字还要你念", "对比类知识用表格或矩阵呈现"],
       "C", {"authors": "Mayer, R. E. (based on Paivio, A.)", "title": "Multimedia Learning (dual coding / redundancy principle)", "source": "Cambridge University Press", "year": "2009", "url": "https://en.wikipedia.org/wiki/Dual-coding_theory", "verification": "canonical"},
       "verified", [("memory-encoding", "train"), ("spatial-reasoning", "train")],
       {},
       contraindications="冗余效应：图文内容完全相同时，会增加负荷而非帮助。"),

    _e("sleep-memory-consolidation", "principle", "neuro", "通用",
       "睡眠是记忆的固化时段，不是可牺牲的",
       "熬夜刷夜学到的内容，第二天记住的远少于睡够的人。",
       "记忆巩固把新形成的、脆弱的记忆痕迹稳定为长期记忆；睡眠（尤其慢波睡眠）在系统巩固中起关键作用。",
       ["保证 7 小时以上睡眠，考前不熬夜", "把新学内容安排在睡前不久做一次轻回顾", "重要复习排在睡前一晚，而非连熬", "午间 20 分钟小睡有助巩固"],
       "B", {"authors": "（综述）Dudai, Y. 等；Walker, M. P., & Stickgold, R.", "title": "Memory consolidation / Sleep-dependent memory consolidation", "source": "Wikipedia 综述条目 / Nature Reviews Neuroscience", "year": "2004+", "url": "https://en.wikipedia.org/wiki/Memory_consolidation", "verification": "verified"},
       "verified", [("memory-encoding", "train"), ("attention-sustain", "train")],
       {"minSleepHours": 7, "preSleepReviewMin": 15, "napMin": 20, "napMaxMin": 30},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["final-exam", "grad-school"]},
       contraindications="午睡超过 30 分钟易进深睡、醒后更困（睡眠惯性）。"),

    _e("circadian-chronotype", "principle", "neuro", "通用",
       "找到你的高效时段，把硬骨头放进那里",
       "人的认知峰值随时间不同（晨型/夜型）；把最难的任务排在个人峰值段，收益最大。",
       "Roenneberg 等提出 chronotype 是个体化的昼夜节律偏好，受基因与作息共同影响，并非懒惰。",
       ["连续一周记录自己哪个时段最清醒", "把最难的科目放到峰值段", "晨型人别把难题留到深夜，夜型人别硬早起刷题", "尽量固定作息，减少社会时差"],
       "C", {"authors": "Roenneberg, T. 等", "title": "Chronotype (circadian preference)", "source": "Journal of Biological Rhythms / Sleep Medicine Reviews", "year": "2004+", "url": "https://en.wikipedia.org/wiki/Chronotype", "verification": "canonical"},
       "verified", [("attention-sustain", "train"), ("metacognitive-regulation", "train")],
       {"peakWindowHint": "07:00-11:00 | 19:00-23:00", "alignHardTaskToPeak": True},
       applicable_when={"phase": ["any"], "persona": {"nightness": "any"}, "task": []}),

    _e("ultradian-rhythm", "principle", "neuro", "通用",
       "注意力有约 90 分钟的起伏周期",
       "专注不是越久越好；一个深度周期后应有短暂休整，否则效率陡降。",
       "超日节律（ultradian rhythm）指约 90 分钟一轮的生理周期，与注意力、警觉水平波动相关。",
       ["把深度任务切成约 90 分钟一节", "每节后休息 15 分钟左右（起身、远眺）", "休息时不刷短视频（会打断恢复）", "一天安排 2-3 个深度节，别贪多"],
       "C", {"authors": "（普及者）Kleitman, N. 的 basic rest-activity cycle", "title": "Basic rest-activity cycle / ultradian rhythm", "source": "生理节律综述", "year": "1960s+", "url": "https://en.wikipedia.org/wiki/Ultradian_rhythm", "verification": "canonical"},
       "verified", [("attention-sustain", "train")],
       {"cycleMin": 90, "breakMin": 15, "maxDeepBlocksPerDay": 3}),

    _e("self-determination-theory", "principle", "psych", "通用",
       "自我决定论：自主、胜任、归属决定内在动机",
       "当学习满足「我自己选的、我做得到、有人一起」三条时，动机最稳。",
       "Deci & Ryan 的 SDT：人有三种基本心理需要——自主（autonomy）、胜任（competence）、归属（relatedness），被满足时内在动机最强。",
       ["给任务留一点自主选择（先学哪科、在哪学）", "把大目标拆到「跳一跳够得着」，制造胜任感", "找搭子或学习小组满足归属", "减少纯外部控制（只为惩罚而学）"],
       "B", {"authors": "Deci, E. L., & Ryan, R. M.", "title": "Self-determination theory of motivation and personality", "source": "American Psychologist / Springer", "year": "2000", "url": "https://en.wikipedia.org/wiki/Self-determination_theory", "verification": "verified"},
       "verified", [("metacognitive-regulation", "train"), ("attention-sustain", "train")],
       {"autonomyChoiceN": 2, "preferStudyWithPeers": True},
       applicable_when={"phase": ["any"], "persona": {"social_radius": "wide"}, "task": []}),

    _e("flow", "principle", "psych", "通用",
       "心流：难度与能力匹配时最投入",
       "任务太难会焦虑、太易会无聊；调到略超能力一点点最容易进入专注状态。",
       "Csikszentmihalyi 提出 flow：挑战与技能匹配、目标清晰、即时反馈时，人会高度投入并失去时间感。",
       ["把任务难度调到略高于当前水平", "给每次学习设清晰的小目标", "移除干扰（手机、通知）", "安排连续不被打断的时间段"],
       "C", {"authors": "Csikszentmihalyi, M.", "title": "Flow: The Psychology of Optimal Experience", "source": "Harper & Row", "year": "1990", "url": "https://en.wikipedia.org/wiki/Flow_(psychology)", "verification": "canonical"},
       "verified", [("attention-sustain", "train"), ("metacognitive-regulation", "train")],
       {"challengeSkillBand": [1.02, 1.15]}),

    _e("implementation-intentions", "principle", "behavior", "通用",
       "实施意图：如果…就…比「我要努力」管用",
       "把计划写成具体的 if-then（何时何地做什么），执行率显著提高。",
       "Gollwitzer 的研究表明，if-then 计划把行为控制权交给情境线索，减少临场决策消耗，从而提升目标达成率。",
       ["写下「如果到图书馆坐下，就先做 25 分钟高数」", "绑定具体时间、地点与动作", "针对已知干扰预设应对（如果手机响了，就先记下再继续）", "一次只加一两条 if-then，别贪多"],
       "B", {"authors": "Gollwitzer, P. M., & Sheeran, P.", "title": "Implementation intentions and goal achievement: A meta-analysis", "source": "Advances in Experimental Social Psychology", "year": "2006", "url": "https://en.wikipedia.org/wiki/Implementation_intention", "verification": "verified"},
       "verified", [("metacognitive-regulation", "train"), ("attention-sustain", "train")],
       {"ifThenCount": 2, "attachToPlace": True},
       applicable_when={"phase": ["any"], "persona": {}, "task": []}),

    _e("habit-formation-loop", "principle", "behavior", "通用",
       "习惯靠重复与稳定情境，而非意志力",
       "在固定情境里重复，行为会逐渐自动化；平均需要约 66 天，个体差异很大。",
       "Lally 等(2010) 追踪日常行为的自动化过程，发现达到自动化平台期平均约 66 天，且漏掉一天影响不大，重要的是恢复。",
       ["把新行为挂到已有的固定锚点后（如晚饭后）", "初期允许中断，重点是第二天回得来", "固定同一时间同一地点", "只培养 1-2 个新习惯，别同时开一堆"],
       "B", {"authors": "Lally, P., van Jaarsveld, C. H. M., Potts, H. W. W., & Wardle, J.", "title": "How are habits formed: Modelling habit formation in the real world", "source": "European Journal of Social Psychology", "year": "2010", "url": "", "verification": "canonical"},
       "verified", [("metacognitive-regulation", "train"), ("attention-sustain", "train")],
       {"habitAnchor": "after-existing-routine", "expectDays": 66}),

    _e("procrastination-regulation", "principle", "psych", "通用",
       "拖延是情绪调节问题，不是时间管理问题",
       "拖的不是没时间，是一想到就难受。解法是降低启动痛苦，而非再加一个番茄钟。",
       "Steel(2007) 的元分析把拖延与冲动性、任务厌恶、延迟折扣联系起来：拖延本质是回避当下的负面情绪。",
       ["把任务缩到小到不可能拒绝（如只做 5 分钟）", "先做最丑的第一步（打开文档、写第一行）", "接纳情绪而非对抗（我知道它让我烦）", "降低任务厌恶：把大任务拆小、先做有趣的部分"],
       "B", {"authors": "Steel, P.", "title": "The nature of procrastination: A meta-analytic and theoretical review", "source": "Psychological Bulletin", "year": "2007", "url": "https://en.wikipedia.org/wiki/Procrastination", "verification": "verified"},
       "verified", [("metacognitive-regulation", "train"), ("attention-sustain", "train")],
       {"firstMicroStepMin": 5, "startRitual": "打开文件并写第一行"},
       applicable_when={"phase": ["any"], "persona": {"nfcc": "any"}, "task": []},
       contraindications="严重且长期影响生活的拖延可能伴随焦虑或抑郁，应寻求学校心理咨询，而非只靠自我调节。"),

    _e("growth-mindset", "principle", "psych", "通用",
       "成长型思维：能力可增长（但别神化它）",
       "相信能力可通过努力提升，有助于面对挫折——但它的实际效应比流行说法小得多。",
       "Dweck 提出固定型与成长型思维。近年大规模复制研究（Sisk 等 2018 元分析）发现其对学业成绩的平均效应很小，且干预效果不稳定。",
       ["把「我不会」改成「我还没学会」", "关注过程与策略，而非天赋归因", "不要用它替代具体的学法（「努力就会好」是廉价的）"],
       "C", {"authors": "Dweck, C. S. (提出); Sisk, V. F. et al. (2018, 元分析)", "title": "Mindset / To what extent and under which circumstances are growth mindsets important to academic achievement?", "source": "Psychological Science", "year": "2006 / 2018", "url": "https://en.wikipedia.org/wiki/Mindset", "verification": "canonical"},
       "contested", [("metacognitive-regulation", "train")],
       {},
       contraindications="有争议：效应量小、复制不稳。可作为心态提示，不得当作提分方案；更不能用「你不够努力」去归因（尤其对基础本就薄弱的同学）。"),

    _e("stress-performance", "principle", "psych", "通用",
       "耶克斯-多德森定律：适度紧张最好，过度就崩",
       "唤醒水平太低（走神）或太高（慌）都不利于表现；中等偏高最优。",
       "Yerkes & Dodson(1908) 提出唤醒与表现的倒 U 关系；后来发现最佳唤醒水平随任务难度变化（难任务要更冷静）。",
       ["考前把紧张重新解读为身体在备战", "难科目考前做深呼吸或简短放松，别继续灌新知识", "用模拟考适应压力情境", "保留固定作息，不要靠熬夜加咖啡硬顶"],
       "C", {"authors": "Yerkes, R. M., & Dodson, J. D.", "title": "The relation of strength of stimulus to rapidity of habit-formation", "source": "Journal of Comparative Neurology and Psychology", "year": "1908", "url": "https://en.wikipedia.org/wiki/Yerkes%E2%80%93Dodson_law", "verification": "canonical"},
       "verified", [("attention-sustain", "train"), ("metacognitive-regulation", "train")],
       {"preExamCalmMin": 10, "simulateUnderPressure": True},
       applicable_when={"phase": ["期末"], "persona": {}, "task": ["final-exam", "cet"]}),

    # ---------------- L1 通用学习法 ----------------
    _e("pomodoro", "method", "study_skill", "通用",
       "番茄工作法：25 分钟专注 + 5 分钟休息",
       "把长任务切成短专注单元，降低启动门槛、维持节奏。",
       "Cirillo 于 1980 年代末提出：以定时器把工作切成专注段与休息段。⚠️ 无同行评议的效力证据，属从业者经验；其有效性的传闻基础与降低启动成本、提供节奏一致。",
       ["设 25 分钟定时器，只做一件事", "响铃后休息 5 分钟（离开座位）", "每 4 个番茄后休息 15-30 分钟", "按自己的专注力调时长（不易专注者用 15/5，深度工作者用 50/10）"],
       "D", {"authors": "Cirillo, F.", "title": "The Pomodoro Technique", "source": "从业者方法（无同行评议证据）", "year": "1980s/2006", "url": "", "verification": "practitioner"},
       "verified", [("attention-sustain", "train"), ("metacognitive-regulation", "train")],
       {"focusMin": 25, "breakMin": 5, "longBreakMin": 20, "rounds": 4, "durations": [25, 50]},
       applicable_when={"phase": ["any"], "persona": {}, "task": []},
       contraindications="无循证效力证据；对进入状态慢的人，硬性 25 分钟打断反而有害——用超日节律的 90 分钟档更合适。"),

    _e("time-blocking", "method", "study_skill", "通用",
       "时间块：给每件事预占一段日历",
       "不是列待办，而是把任务放到具体时段；能看见时间去哪了。",
       "把任务从清单映射到日历，减少「什么时候做」的临场决策。属实践方法，证据等级 D。",
       ["先把固定课程与通勤占位", "给每件事预估时长并放进具体时段", "预留 20% 缓冲，别排满", "每天结束时把没完成的挪到新时段"],
       "D", {"authors": "（实践方法）Newport, C. 等推广", "title": "Time blocking", "source": "从业者方法", "year": "2000s+", "url": "", "verification": "practitioner"},
       "verified", [("metacognitive-regulation", "train")],
       {"bufferRatio": 0.2, "dayStart": "07:00", "dayEnd": "23:00"},
       applicable_when={"phase": ["any"], "persona": {"planning": "planned"}, "task": []}),

    _e("deep-work", "method", "study_skill", "通用",
       "深度工作：一段无人打扰的高强度专注",
       "同样 2 小时，无干扰的深度工作产出远高于随时被打断的状态。",
       "Newport 提出：深度工作是在无干扰状态下对认知要求高的任务。核心机制与注意力残留（attention residue）一致——切换成本高昂。",
       ["固定一个 90 分钟深度段，关通知", "把浅任务（回消息、杂事）集中到固定时段批量处理", "用环境信号告诉别人我在深度工作", "一天 2-3 个深度段已是高产"],
       "D", {"authors": "Newport, C.", "title": "Deep Work: Rules for Focused Success in a Distracted World", "source": "Grand Central Publishing", "year": "2016", "url": "", "verification": "practitioner"},
       "verified", [("attention-sustain", "train"), ("metacognitive-regulation", "train")],
       {"deepBlockMin": 90, "maxDeepBlocksPerDay": 3, "notifyOff": True},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["mcm", "grad-school"]}),

    _e("eisenhower-matrix", "method", "study_skill", "通用",
       "四象限：先分轻重缓急，再动手",
       "按重要、紧急两维把任务分类，避免被紧急但不重要的事淹没。",
       "源自艾森豪威尔的优先级思想，后由 Covey 系统化。属决策辅助工具（D 级）。",
       ["把所有任务按重要与紧急两维落格", "重要不紧急（复习、积累）主动排进时间块", "紧急不重要（临时通知）尽快处理或委派", "既不重要也不紧急的一律砍掉"],
       "D", {"authors": "Covey, S. R. (系统化)", "title": "The 7 Habits of Highly Effective People（四象限）", "source": "从业者/管理方法", "year": "1989", "url": "", "verification": "practitioner"},
       "verified", [("metacognitive-regulation", "train"), ("problem-decomposition", "train")],
       {"reviewCadence": "daily"}),

    _e("cornell-notes", "method", "study_skill", "通用",
       "康奈尔笔记：一页分栏，逼出主动加工",
       "把笔记页分成线索、笔记、总结三栏，复习时遮住笔记用线索自我提问。",
       "康奈尔大学推广的版式；其价值在于把笔记变成可自我测验的结构。证据多为课堂实践研究，等级 C/D。",
       ["页面右侧 2/3 记笔记主体", "左侧 1/3 写关键词或问题", "底部留几行写本页总结", "复习时遮住右侧，用左侧线索回忆"],
       "D", {"authors": "（教学实践）Cornell University", "title": "The Cornell Note-taking System", "source": "大学学习中心资料", "year": "1950s+", "url": "", "verification": "practitioner"},
       "verified", [("memory-encoding", "train"), ("metacognitive-regulation", "train")],
       {"cueColumnRatio": 0.33},
       contraindications="纯抄写的康奈尔笔记没有意义——关键在自己出线索、遮住复述。"),

    _e("zettelkasten", "method", "study_skill", "通用",
       "卡片盒笔记：通过链接让知识长成网络",
       "把每条想法写成独立卡片并互相链接，形成可复用的思考网络。",
       "Luhmann 的卡片盒法。属实践方法（D 级）；机制上与精细加工、生成效应一致（写作加链接等于深加工）。",
       ["一条卡片只放一个想法", "写卡片时用自己的话", "主动把新卡片链接到已有卡片", "定期回看并建立索引"],
       "D", {"authors": "Luhmann, N.（方法）; Ahrens, S.（普及）", "title": "How to Take Smart Notes", "source": "从业者方法", "year": "2017", "url": "", "verification": "practitioner"},
       "verified", [("literature-synthesis", "train"), ("memory-encoding", "train")],
       {"oneIdeaPerNote": True, "requireLink": True},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["mcm", "grad-school"]},
       contraindications="对只需速记应付考试的场景过重；它是长期知识生产工具，不是应试工具。"),

    _e("feynman-technique", "method", "study_skill", "通用",
       "费曼技巧：讲给外行听，卡住处就是漏洞",
       "用自己的话把概念讲到外行能懂，讲不通的地方就是你其实没懂的地方。",
       "以物理学家费曼命名的通俗说法，本质是自我解释（self-explanation）加生成。D 级方法，但机制有 C 级证据支撑。",
       ["选一个概念，在空白页写下它", "假装讲给一个完全不懂的人", "卡壳处回到资料，重新弄懂", "简化语言、用类比，直到通畅"],
       "D", {"authors": "（通俗命名）; 机制依据 Dunlosky et al. 2013 的 self-explanation", "title": "Feynman Technique", "source": "普及方法（机制有综述支撑）", "year": "—", "url": "", "verification": "practitioner"},
       "verified", [("argumentation", "train"), ("memory-encoding", "train"), ("metacognitive-regulation", "train")],
       {"explainOutLoud": True},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["final-exam", "mcm"]}),

    _e("sq3r", "method", "study_skill", "通用",
       "SQ3R：带着问题读教材",
       "浏览、提问、精读、复述、复习五步，把被动阅读变成主动提取。",
       "Robinson(1946) 提出的阅读法。多项课堂研究支持其优于纯阅读，但效应中等。C/D 级。",
       ["Survey 浏览：看标题、图表、小结", "Question 提问：把标题改写成问题", "Read 精读：带着问题读", "Recite 复述：合书回答自己的问题", "Review 复习：隔天再过一遍"],
       "C", {"authors": "Robinson, F. P.", "title": "Effective Study（SQ3R）", "source": "Harper & Row", "year": "1946", "url": "", "verification": "canonical"},
       "verified", [("memory-encoding", "train"), ("metacognitive-regulation", "train")],
       {"questionFirst": True},
       contraindications="对陌生领域需先有基础框架，否则提问会流于表面。"),

    _e("spaced-repetition-tool", "method", "study_skill", "通用",
       "间隔重复软件：把复习节奏交给算法",
       "Anki 类工具按遗忘曲线安排复习，把「什么时候复习」这件事自动化。",
       "间隔重复是循证方法（见 spacing-effect）；把 Leitner 盒或 Anki 算法用于排程，可稳定维持长期记忆。",
       ["把知识点做成问答卡片（而非抄书）", "卡片要原子化，一问一答", "每天固定时间清当天到期卡片", "宁可少而精，别一次性导入几百张"],
       "B", {"authors": "（工具）Anki; 原理 Ebbinghaus / Cepeda", "title": "Spaced repetition software", "source": "工具+循证原理", "year": "—", "url": "https://en.wikipedia.org/wiki/Spaced_repetition", "verification": "verified"},
       "verified", [("memory-encoding", "train")],
       {"dailyReviewCapMin": 30, "intervalsDays": [1, 3, 7, 15, 30]},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["cet", "final-exam", "grad-school"]},
       contraindications="做卡片本身很费时；对理解型（非记忆型）内容收益有限，别把所有科目都做成卡片。"),

    _e("exam-strategy", "exam", "exam", "通用",
       "应试三板斧：真题驱动 + 错题本 + 模考",
       "以真题定方向，以错题定重点，以模考定节奏。",
       "应试是有限规则下的表现优化。真题框定考查范围与风格；错题暴露个人薄弱；模考训练时间分配与压力适应。属实践共识（C/D）。",
       ["先刷 3 套真题，标记高频考点与题型", "建错题本，只记错因不抄题", "每 3-5 天做一次限时模考", "模考后分析：超时的题、反复错的点、该放弃的题"],
       "C", {"authors": "（综合实践共识）", "title": "真题驱动 + 错题本 + 模考", "source": "备考实践共识", "year": "—", "url": "", "verification": "practitioner"},
       "verified", [("memory-encoding", "train"), ("metacognitive-regulation", "train"), ("attention-sustain", "train")],
       {"sprintLeadDays": 14, "mockIntervalDays": 3, "minMockCount": 3, "errorLogByCause": True},
       applicable_when={"phase": ["期末"], "persona": {}, "task": ["cet", "final-exam", "grad-school"]},
       contraindications="只刷题不理解，遇到变式题就崩；真题驱动需与检索练习、精细追问配合。"),

    _e("mock-exam-analysis", "exam", "exam", "通用",
       "模考后必须做卷面分析，不然白考",
       "模考的价值在复盘：超时分布、错因归类、策略调整。",
       "把模考当数据采集：区分不会、看错、算错、没时间，不同错因对应不同动作。C/D。",
       ["给每道错题标错因（知识/粗心/时间/理解）", "统计各题型耗时，找出时间黑洞", "定下下一场的答题顺序与取舍策略", "把知识型错误回填到错题本"],
       "D", {"authors": "（备考实践共识）", "title": "模考复盘", "source": "备考实践共识", "year": "—", "url": "", "verification": "practitioner"},
       "verified", [("metacognitive-regulation", "train")],
       {"errorTaxonomy": ["knowledge", "careless", "time", "comprehension"]},
       applicable_when={"phase": ["期末"], "persona": {}, "task": ["cet", "final-exam", "grad-school"]}),

    _e("note-taking-active", "method", "study_skill", "通用",
       "笔记要加工不要搬运",
       "抄板书是低效的；把笔记写成自己的话、问题与联系才有价值。",
       "与生成效应、精细加工一致：加工性笔记（改写、提问）优于逐字记录。B/C。",
       ["用自己的话改写", "记为什么和怎么用，不只记是什么", "留白，课后补上联系", "把课堂笔记当场转成 2-3 个自测问题"],
       "C", {"authors": "（综述）Dunlosky et al. (2013) 等", "title": "Generative note-taking", "source": "学习科学综述", "year": "2013", "url": "", "verification": "canonical"},
       "verified", [("memory-encoding", "train"), ("argumentation", "train")],
       {"paraphraseRequired": True, "questionsPerPage": 2}),

    _e("environment-design", "behavior", "behavior", "通用",
       "环境设计：让好行为更容易、坏行为更麻烦",
       "改变环境比改变意志力省力：把手机放远、把书放近。",
       "行为设计的核心：提高目标行为的便利度、抬高干扰行为的摩擦（与习惯回路、实施意图同源）。C/D。",
       ["学习时把手机放到另一个房间或开飞行模式", "把要学的东西提前摊开在桌上", "固定一个只用来学习的位置", "用网站拦截器挡掉短视频与游戏"],
       "C", {"authors": "（行为设计综合）", "title": "Choice architecture / friction design", "source": "行为科学综述", "year": "—", "url": "", "verification": "canonical"},
       "verified", [("attention-sustain", "train"), ("metacognitive-regulation", "train")],
       {"phoneOutOfRoom": True, "blockDistractions": True}),

    _e("metacognitive-monitoring", "principle", "cognitive", "通用",
       "元认知：知道自己哪里不会最值钱",
       "学习最大的陷阱是以为会了。定期自测校准判断，把时间投到真正不会的地方。",
       "元认知包括计划、监控、调节。判断学习（JOL）常高估掌握程度，这就是重读错觉的来源。A/B。",
       ["学完立刻自测，而不是感觉懂了就走", "给每个知识点打会、半会、不会标签", "把时间优先投给半会与不会", "每周做一次「我以为会但实际不会」的对照"],
       "B", {"authors": "（综述）Dunlosky & Metcalfe 等", "title": "Metacognition and judgments of learning", "source": "学习科学综述", "year": "—", "url": "", "verification": "canonical"},
       "verified", [("metacognitive-regulation", "train"), ("memory-encoding", "require")],
       {"selfAssessCadenceDays": 1, "confidenceVsAccuracyCheck": True},
       applicable_when={"phase": ["any"], "persona": {"nfc": "any"}, "task": ["final-exam", "grad-school"]}),

    # ---------------- L2 学科学法 ----------------
    _e("science-math-method", "discipline", "discipline", "理科",
       "理科：定义→定理→例题→推导的闭环",
       "理科不是背结论，是能把结论推出来、并知道它从哪来。",
       "理科知识是演绎结构：定义框定对象，定理给出关系，例题展示用法。理解等于能重构推导链。",
       ["每个定理都追问它是从哪来的、条件为什么必需", "盖住例题答案自己推一遍", "整理定义、定理、常用变形的三栏", "做完题回到定义，检查自己用的是不是原始定义"],
       "C", {"authors": "（学习科学 + 学科教学共识）", "title": "理科学习的演绎结构与推导闭环", "source": "学科教学共识", "year": "—", "url": "", "verification": "canonical"},
       "verified", [("logical-reasoning", "train"), ("abstraction-modeling", "train"), ("problem-decomposition", "train")],
       {"deriveBeforeCheck": True, "definitionReviewRatio": 0.3},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["final-exam", "grad-school", "mcm"]},
       contraindications="只推不练会懂而不会做；推导与题目练习需交替。"),

    _e("engineering-method", "discipline", "discipline", "工科",
       "工科：从问题出发，边做边建直觉",
       "工科靠做出来：动手、仿真、调参、失败修正的循环。",
       "工程知识是可造物的知识，与具体系统耦合。项目与实践驱动的学习更贴合其结构。",
       ["先明确要造一个什么东西，再倒推需要学什么", "尽早跑通一个最小可运行版本（先跑起来再优化）", "用仿真或实验验证直觉，别停在应该对", "把每次失败的原因记下来，形成工程直觉卡"],
       "C", {"authors": "（工程教育共识：项目式学习）", "title": "Project-based engineering learning", "source": "工程教育共识", "year": "—", "url": "", "verification": "canonical"},
       "verified", [("experiment-design", "train"), ("computational-thinking", "train"), ("problem-decomposition", "train")],
       {"minimalViableFirst": True, "simulateBeforeClaim": True},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["guangdianbei", "mcm"]},
       contraindications="只做项目不补理论，会停在能跑但说不清为什么，考试与深度问题会露馅。"),

    _e("humanities-method", "discipline", "discipline", "文科",
       "文科：读—议—写，三件事都要练",
       "文科能力体现在理解与表达：会读（提取论点）、会议（批判）、会写（结构化论证）。",
       "文科知识的组织是论点、证据、推理的论证结构，记忆性内容只是载体。",
       ["读文献先找作者主张是什么、凭什么", "用一句话概括每段，训练提取论点", "写作先搭论点与论据的骨架再填充", "用回忆加复述背记事实性内容（配合间隔重复）"],
       "C", {"authors": "（通识教育共识）", "title": "文科的读议写三练", "source": "通识教育共识", "year": "—", "url": "", "verification": "canonical"},
       "verified", [("argumentation", "train"), ("literature-synthesis", "train"), ("memory-encoding", "train")],
       {"readingClaimExtract": True, "outlineBeforeWrite": True},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["final-exam"]}),

    # ---------------- L3 竞赛 / 项目 ----------------
    _e("mcm-playbook", "playbook", "competition", "理科",
       "数学建模打法：抽象→假设→建模→求解→验证→论文",
       "数模考的不是会不会某个模型，是把开放问题变成可解模型并说清楚的能力。",
       "建模竞赛的评分核心是建模过程的合理性、结果的解释力与论文表达，而非模型复杂度。全部时间本质上是抽象建模、统计推断、计算思维、表达论证四类元能力的调用。",
       ["审题：把问题拆成几个可独立回答的子问题", "明确假设并写下来（假设是模型的边界）", "选模型：优先能解释、能验证的简单模型", "求解：能算的用数值方法，善用工具", "验证：做敏感性分析，与常识或数据对照", "写作：结果导向，图表说话，摘要定生死"],
       "D", {"authors": "（竞赛实践共识）COMAP/MCM 评审关注点", "title": "Mathematical Contest in Modeling 备战方法", "source": "竞赛实践共识", "year": "—", "url": "https://www.comap.com/contests/mcm-icm", "verification": "practitioner"},
       "verified", [("abstraction-modeling", "train"), ("stats-inference", "train"), ("computational-thinking", "train"), ("argumentation", "train"), ("literature-synthesis", "train")],
       {"phases": ["审题", "假设", "建模", "求解", "验证", "写作"], "simplerModelPreferred": True, "sensitivityRequired": True},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["mcm"]},
       tasks=[("mcm", 1.0)]),

    _e("mcm-3day-timeline", "playbook", "competition", "理科",
       "数模 3 天赛程：时间线怎么分",
       "3 天不是写论文三天，而是选题、建模、求解、写作四条线并行。",
       "把赛程当项目管理：前紧后松会崩，前松后紧也崩；关键是第一天定题、第二天出结果、第三天全用来写作与打磨。",
       ["Day1 上午：读题、查资料、定题（最晚中午必须定）", "Day1 下午到 Day2 上午：搭模型、跑出初步结果", "Day2 下午到夜里：补全求解、做敏感性分析", "Day3 全天：写作加图表加摘要反复打磨（摘要最重要）", "全程：每晚留 5-6 小时睡眠，别熬穿第一晚"],
       "D", {"authors": "（竞赛实践共识）", "title": "MCM 72 小时赛程分配", "source": "竞赛实践共识", "year": "—", "url": "https://www.comap.com/contests/mcm-icm", "verification": "practitioner"},
       "verified", [("problem-decomposition", "train"), ("argumentation", "train"), ("metacognitive-regulation", "train")],
       {"totalHours": 72, "decideTopicByHour": 12, "writingBlockHours": 20, "sleepMinHours": 5},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["mcm"]},
       tasks=[("mcm", 1.0)]),

    _e("literature-search", "method", "competition", "通用",
       "文献检索：三层漏斗找得又快又准",
       "先用关键词铺开，再用引文追溯收窄，最后按质量筛选。",
       "检索是提出问题、转换关键词、筛选、饱和的循环；引文追溯（往前找参考文献、往后找施引文献）能快速定位领域核心文献。",
       ["把问题拆成 2-4 个核心概念，各找同义词", "用数据库（知网、Web of Science、Google Scholar）组合检索", "找到一篇好文献后，正查参考文献、反查施引文献", "按权威期刊、被引数、年份筛选，读到信息饱和为止"],
       "C", {"authors": "（信息素养共识）", "title": "文献检索与筛选方法", "source": "信息素养教育共识", "year": "—", "url": "", "verification": "canonical"},
       "verified", [("literature-synthesis", "train"), ("metacognitive-regulation", "train")],
       {"forwardBackwardTrace": True, "saturationStop": True},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["mcm", "grad-school"]}),

    _e("experiment-design", "method", "competition", "工科",
       "实验设计：变量、对照、误差三者缺一不可",
       "好的实验能排除其他解释；差的实验只能产生一个数字。",
       "受控实验的基本原则：只改一个自变量、设对照组、控制混淆变量、评估误差与可重复性。",
       ["明确自变量、因变量与控制变量", "设置对照组（最好随机分配）", "多测几组，报告均值与离散度而非单点", "记录所有条件，确保别人能重复"],
       "C", {"authors": "（科研方法共识）", "title": "Controlled experiment design", "source": "科研方法共识", "year": "—", "url": "", "verification": "canonical"},
       "verified", [("experiment-design", "train"), ("stats-inference", "train")],
       {"minReplicates": 3, "controlRequired": True, "reportDispersion": True},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["guangdianbei", "mcm"]}),

    _e("team-project-management", "playbook", "competition", "通用",
       "竞赛团队：分工要按能力类型，不按人头",
       "团队效率取决于角色是否覆盖建模、计算、写作、统筹，而非人多。",
       "竞赛是短期高强度项目：需要明确角色、定期同步、单一决策点。分工应按元能力组合，而非简单平均。",
       ["按元能力分工：建模、编程计算、写作、统筹各有人", "设一个定题拍板的角色，避免反复摇摆", "每天固定两次短同步（早定计划、晚对进度）", "写作线不能等到最后一天才开始"],
       "D", {"authors": "（项目管理共识）", "title": "竞赛团队角色分工", "source": "项目管理共识", "year": "—", "url": "", "verification": "practitioner"},
       "verified", [("argumentation", "train"), ("problem-decomposition", "train"), ("metacognitive-regulation", "train")],
       {"roles": ["建模", "计算", "写作", "统筹"], "syncPerDay": 2, "singleDecider": True},
       applicable_when={"phase": ["any"], "persona": {}, "task": ["mcm", "guangdianbei"]}),
]


# ============================================================
# 四、拒收清单（已证伪 / 过度简化 —— 只记录，不入库）
# ============================================================
# 本清单存在的意义：让「为什么没有它」可被审计（对应项目「审计工具自身会骗人」的教训）。
REJECTED = [
    {"slug": "learning-styles", "name": "学习风格（视觉型/听觉型/动觉型）",
     "reason": "VAK/VARK 学习风格与教学匹配的假设缺乏实证支持，多项研究未发现匹配教学带来收益。属已证伪。"},
    {"slug": "left-right-brain", "name": "左脑逻辑/右脑创造",
     "reason": "脑区分工的流行说法被过度简化，不存在左脑型或右脑型人格。属伪科学。"},
    {"slug": "ten-percent-brain", "name": "人类只用了 10% 大脑",
     "reason": "已有明确神经科学反证。属都市传说。"},
    {"slug": "one-size-pomodoro", "name": "番茄钟 25 分钟适合所有人",
     "reason": "无循证依据；个体专注节律差异大，硬套会打断深度状态。"},
    {"slug": "learning-pyramid", "name": "学习金字塔（听讲留存 5%、教别人 90%）",
     "reason": "流传的具体百分比数字查无实证来源，系误传。"},
    {"slug": "mozart-effect", "name": "听莫扎特能变聪明（莫扎特效应）",
     "reason": "原始效应是短暂的空间推理小提升，被媒体放大为变聪明，未能复制。"},
]
